variables:

  MSBuildPath: "C:\Program Files (x86)\MSBuild\14.0\Bin"
  LocalKBPath: "C:\KBs\Estimaciones"
  ServerUserName: "sa_jenkins_genexus"
  ServerPassword: '567NTb0L4L4wjK4hZkAl'

  UpdateMSBuildScript: |
                       "$(MSBuildPath)\\MSBuild.exe" "C:\\Users\\nsalazar\\Documents\\Git\\Azure_Pipelines\\Pruebas\\AzurePipeline001\\msbuild\\Update.msbuild" 
                       /p:KBPath="$(LocalKBPath)_" 
                       /p:ServerUserName=$(ServerUserName) 
                       /p:ServerPassword=$(ServerPassword)  
                       /t:Update

  BuildAllMSBuildScript: |
                         "$(MSBuildPath)\\MSBuild.exe" "C:\\Users\\nsalazar\\Documents\\Git\\Azure_Pipelines\\Pruebas\\AzurePipeline001\\msbuild\\BuildAll.msbuild" 
                         /p:KBPath="$(LocalKBPath)"
                         /p:ForceRebuild="false"
                         /p:CompileMains="true"
                         /p:DetailedNavigation="false"
                         /p:FailIfReorg="false"
                         /p:DoNotExecuteReorg="false" 
                         /t:Build

trigger:
  branches:
    include:
      - main

pool:
  name: 'AzureAgentPool'

stages:

  - stage: UpdateFromGXServer
    displayName: "Actualizar KB desde GXServer"
    jobs:
      - job: UpdateJob
        displayName: "Update GeneXus KB"
        steps:
          - powershell: |
              & "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" "C:\Users\nsalazar\Documents\Git\Azure_Pipelines\Pruebas\AzurePipeline001\msbuild\Update.msbuild" /p:KBPath="$(LocalKBPath)" /p:ServerUserName=$(ServerUserName) /p:ServerPassword=$(ServerPassword) /t:Update 

  # - stage: BuildKB 
  #   displayName: "Build de GeneXus KB"
  #   dependsOn: UpdateFromGXServer
  #   jobs:
  #     - job: BuildJob
  #       displayName: "Build GeneXus KB"
  #       steps:
  #         - powershell: $(BuildAllMSBuildScript)

  # - stage: Deploy
  #   displayName: "Despliegue al ambiente de desarrollo"
  #   dependsOn: Build
  #   jobs:
  #     - job: DeployJob
  #       displayName: "Deploy GeneXus KB"
  #       steps:
  #         - task: PowerShell@2
  #           inputs:
  #             targetType: 'inline'
  #             script: |
  #               # Comando de despliegue específico; este comando puede variar según el ambiente de desarrollo
  #               # Ejemplo: Copiar archivos al servidor IIS o ejecutar script de despliegue en Docker
  #               # Ejemplo para IIS:
  #               Copy-Item -Path "C:\path\to\KB\output" -Destination "\\DevServer\inetpub\wwwroot\YourApp" -Recurse -Force
